
export const ORDER_URL = 'ORDER_URL';
export const ORDER_DATA = 'ORDER_DATA';
export const ORDER_PRICE = 'ORDER_PRICE';
export const ORDER_IMAGE = 'ORDER_IMAGE';
export const ORDER_NAME = 'ORDER_NAME';
export const ORDER_CHECK_IN_DATE = 'ORDER_CHECK_IN_DATE';
export const ORDER_CHECK_OUT_DATE = 'ORDER_CHECK_OUT_DATE';
export const ORDER_SUB_DATA = 'ORDER_SUB_DATA';
export const ORDER_SUB_NAME = 'ORDER_SUB_NAME';
export const GET_HOTELS_DATA = 'GET_HOTELS_DATA';
export const GET_HOTELS_DATA_REQUEST = 'GET_HOTELS_DATA_REQUEST';
export const GET_HOTELS_DATA_SUCCESS = 'GET_HOTELS_DATA_SUCCESS';
export const GET_HOTELS_DATA_ERROR = 'GET_HOTELS_DATA_ERROR';
export const GET_CURRENT_HOTEL = 'GET_CURRENT_HOTEL';
export const GET_SEARCH_VALUES = 'GET_SEARCH_VALUES';





